{% set name = "window-ops" %}
{% set version = "0.0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/window_ops-{{ version }}.tar.gz
  sha256: 4c0d4686c50ba1fc1de7d41da706b57118d8fb45531e5a23f06104f804788c1d

build:
  number: 1
  skip: true  # [s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - numba
    - numpy
    - python

test:
  imports:
    - window_ops
  
  requires:
    - pip

  commands:
    - pip check

about:
  doc_url: https://github.com/jmoralez/window_ops
  dev_url: https://github.com/jose-moralez/window_ops
  home: https://github.com/jose-moralez/window_ops
  summary: Implementations of window operations such as rolling and expanding.
  description: |
    This library is intended to be used as an alternative to pd.Series.rolling and pd.Series.expanding 
    to gain a speedup by using numba optimized functions operating on numpy arrays. 
    There are also online classes for more efficient updates of window statistics.

  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmoralez
